runtime: nodejs20
env: standard

handlers:
  # serve static files
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$

  # Catch all handler to index.html
  - url: /.*
    static_files: build/index.html
    secure: always
    redirect_http_response_code: 301
    upload: buid/index.html
